# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        enviroment:
          FLASK_CONFIG: testing


      - image: mysql:latest
        enviroment:
        - MYSQL_ROOT_PASSWORD=1234
        - MYSQL_PASSWORD=1234
        - MYSQL_USER=root

        command: |
          sudo apt install git -y
          git clone https://github.com/FoodSQL/MySouffle
          cd MySouffle
          mysql -uroot -p1234 my_chef < schema00.sql

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: "sudo pip install -e ."

      # - run:
      #    name: setup db

      # run tests!
      - run:
          name: run tests
          command: "python setup.py test"

      - store_artifacts:
          path: test-reports
          destination: test-reports
